version: '2'

services:
  web:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://udacity:capstone@db/capstone
    ports:
      - "80:80"
      - "9191:9191"
  db:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
