"""user language table

Revision ID: 2f4bbdf6293
Revises: None
Create Date: 2016-09-20 16:29:53.372217

"""

# revision identifiers, used by Alembic.
revision = '2f4bbdf6293'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_language',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_language')
    ### end Alembic commands ###
