"""adding language_id to user_language

Revision ID: df9e2fefbd
Revises: 22ba47e67cc
Create Date: 2016-10-13 11:21:09.342090

"""

# revision identifiers, used by Alembic.
revision = 'df9e2fefbd'
down_revision = '22ba47e67cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('language_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'language_id')
    ### end Alembic commands ###
